<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15225" started-at="2019-12-19T11:58:13Z" finished-at="2019-12-19T11:58:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15225" started-at="2019-12-19T11:58:13Z" finished-at="2019-12-19T11:58:29Z">
      <class name="qa.com.test.testcases.RegisterTestcase">
        <test-method status="PASS" signature="setupTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="setupTest" is-config="true" duration-ms="364" started-at="2019-12-19T17:28:13Z" finished-at="2019-12-19T17:28:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="beforeTest" is-config="true" duration-ms="5533" started-at="2019-12-19T17:28:13Z" finished-at="2019-12-19T17:28:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="EmailFacebookRegister()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="EmailFacebookRegister" duration-ms="18" started-at="2019-12-19T17:28:19Z" finished-at="2019-12-19T17:28:19Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at qa.com.test.testcases.TestData.dataSetUp(TestData.java:20)
	at qa.com.test.testcases.RegisterTestcase.EmailFacebookRegister(RegisterTestcase.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmailFacebookRegister -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="afterTest" is-config="true" duration-ms="106" started-at="2019-12-19T17:28:19Z" finished-at="2019-12-19T17:28:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="beforeTest" is-config="true" duration-ms="4728" started-at="2019-12-19T17:28:19Z" finished-at="2019-12-19T17:28:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="GoogleRegisterTestcase()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="GoogleRegisterTestcase" duration-ms="3" started-at="2019-12-19T17:28:24Z" finished-at="2019-12-19T17:28:24Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at qa.com.test.testcases.TestData.dataSetUp(TestData.java:20)
	at qa.com.test.testcases.RegisterTestcase.GoogleRegisterTestcase(RegisterTestcase.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoogleRegisterTestcase -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="afterTest" is-config="true" duration-ms="64" started-at="2019-12-19T17:28:24Z" finished-at="2019-12-19T17:28:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="beforeTest" is-config="true" duration-ms="4690" started-at="2019-12-19T17:28:24Z" finished-at="2019-12-19T17:28:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="RegisterManualEmailPasswordcorrect()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="RegisterManualEmailPasswordcorrect" duration-ms="2" started-at="2019-12-19T17:28:29Z" finished-at="2019-12-19T17:28:29Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\Swathi\Documents\testdata.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at qa.com.test.testcases.TestData.dataSetUp(TestData.java:20)
	at qa.com.test.testcases.RegisterTestcase.RegisterManualEmailPasswordcorrect(RegisterTestcase.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterManualEmailPasswordcorrect -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="afterTest" is-config="true" duration-ms="58" started-at="2019-12-19T17:28:29Z" finished-at="2019-12-19T17:28:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:qa.com.test.testcases.RegisterTestcase@6767c1fc]" name="tearDownTest" is-config="true" duration-ms="0" started-at="2019-12-19T17:28:29Z" finished-at="2019-12-19T17:28:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- qa.com.test.testcases.RegisterTestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
